version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9092:9092"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
 
  db:
    image: mysql:8.0
    container_name: sofbiblio-db-1
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=sofbiblio_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 5
 
networks:
  app-network:
    driver: bridge
 
volumes:
  db-data:
 